[package]
name = "neuch"
version = "0.1.0"
edition = "2021"

[dependencies]
hecs = "0.10.5"
aseprite = "0.1.3"
raylib = "5.0.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
include_dir = "0.7.4"
enum-iterator = "2.1.0"
